name: Dispatch-Deployment

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - main

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploying changes
    runs-on: [self-hosted, derp]
    timeout-minutes: 5
    steps:
      - name: Pull changes
        run: |
          cd ~/dispatch-portal
          git checkout main
          git pull
      - name: Build client
        run: |
          cd ~/dispatch-portal
          npm i
          CI=false npm run build
      - name: Copy & paste build files
        run: |
          rm -rfv /var/www/dispatch-portal/*
          cp -r ~/dispatch-portal/client/build/* /var/www/dispatch-portal
