name: Staging-Deployment

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - staging

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploying changes
    runs-on: [self-hosted, derp]
    timeout-minutes: 5
    steps:
      - name: Pull changes
        run: |
          cd ~/dispatchportal-staging
          git checkout staging
          git pull
      - name: Install Server Dependencies
        run: |
          cd server
          npm i
      - name: Reload pm2 test-api
        run: |
          pm2 reload test-api
