name: Staging-Deployment

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - staging

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploying changes
    runs-on: [self-hosted, derp]
    timeout-minutes: 5
    steps:
      - name: Pull changes
        run: |
          cd ~/dispatch-staging
          git checkout staging
          git pull
      - name: Install Server Dependencies
        run: |
          cd ~/dispatch-staging/server
          npm i
      - name: Reload pm2 test-api
        run: |
          pm2 reload test-api
      - name: Build Client
        run: |
          cd ~/dispatch-staging/client
          npm run build
      - name: Copy & paste build files
        run: |
          rm -rfv /var/www/dispatch-staging/*
          mkdir /var/www/dispatch-staging/client
          cp -r ~/dispatch-staging/client/build/* /var/www/dispatch-staging/client
