# name: Staging-Deployment

# #############################
# # Start the job on all push #
# #############################
# on:
#   push:
#     branches:
#       - staging

# ###############
# # Set the Job #
# ###############
# jobs:
#   deploy:
#     name: Deploying changes
#     runs-on: [self-hosted, derp]
#     timeout-minutes: 5
#     steps:
#       - name: Pull changes
#         run: |
#           cd ~/dispatch-staging/client
#           git checkout staging
#           git pull
#       - name: Build client
#         run: |
#           cd ~/dispatch-staging/client
#           npm i
#           CI=false npm run build
#       - name: Copy & paste build files
#         run: |
#           rm -rfv /var/www/dispatch-staging/*
#           mkdir /var/www/dispatch-staging
#           cp -r ~/dispatch-staging/client/build/* /var/www/dispatch-staging
